services:
  - type: web
    name: nnnab
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_APP_URL
        value: https://nnnab.onrender.com
