services:
  - type: web
    name: nnnab
    env: node
    plan: starter
    memory: 512MB
    buildCommand: |
      corepack enable
      pnpm install
      pnpm run build
    startCommand: pnpm start
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_APP_URL
        value: https://nnnab.onrender.com
